CREATE TABLE [dbo].[Image]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(50) NULL, 
    [ObjectTypeId] INT NOT NULL, 
    [VolumeId] UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES [PhotoAlbum](Id), 
	[Order] INT NULL, 
    [Content] IMAGE NOT NULL, 
)
