CREATE TABLE [dbo].[Image]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(50) NULL, 
    [ObjectTypeId] INT NOT NULL, 
    [AlbumId] UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES [PhotoAlbum](Id), 
    [ImageTypeId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [ImageType](Id),
	[ObjectToCoverId] UNIQUEIDENTIFIER NULL,
	[ObjectToCoverTypeId] UNIQUEIDENTIFIER NULL,
	[Order] INT NULL, 
    [Content] IMAGE NOT NULL, 
)
